global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#evgeny_samsonov'
