---
version: '3.3'

services:
  db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db

  post:
    build: ../src/post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net

  comment:
    build: ../src/comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net

  ui:
    build: ../src/ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
