---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "comment.fullname" . }}-db
  labels:
    app: reddit
    component: mongo
    comment-db: "true"
    release: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.database.port }}
      protocol: TCP
      targetPort: {{ .Values.database.port }}
  selector:
    app: mongodb
    release: {{ .Release.Name }}
